# Generated by Django 5.1.1 on 2025-06-26 09:17

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Обязательное поле. Не больше 150 символов. Только буквы, цифры и символы @/./+/-/_', max_length=150, unique=True, validators=[users.validators.username_validator], verbose_name='Логин'),
        ),
    ]
