# Generated by Django 5.1.1 on 2025-06-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_category_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='image',
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
