# Generated by Django 5.1.1 on 2025-06-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_category_options_alter_genre_options'),
        ('reviews', '0005_remove_title_image_remove_title_rating'),
    ]

    operations = [
    ]
